# Generated by Django 5.2.3 on 2025-06-10 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_galeria/')),
                ('legenda', models.TextField(blank=True, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('aprovada', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to=settings.AUTH_USER_MODEL)),
                ('curtidas', models.ManyToManyField(blank=True, related_name='fotos_curtidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='galeria.foto')),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
    ]
